### ISSUE TITLE
--no-parent causes legitimate files to be on a blacklist

### ISSUE THREAD

**Issue by mruprich** [rockdaboot/wget2#308] opened 2024-03-25 15:36 UTC
With this command:
```
# wget2 -d -r -l1 --no-parent --directory-prefix rpms -A ".rpm" https://kojipkgs.fedoraproject.org//work/tasks/8411/115298411/
```
all of the files from 'https://kojipkgs.fedoraproject.org//work/tasks/8411/115298411/' dir that have the .rpm extension should be downloaded. At least that used to work with old wget. With wget2, all the files, including those with .rpm extension are blacklisted and not downloaded. So the number of downloaded files is 0. Here are pieces of the debug log:
```
.fedoraproject.org/work/tasks/8411/115298411/cyrus-imapd-debuginfo-3.8.2-1.fc41.x86_64.rpm' not followed (parent ascending not allowed)
Adding URL: https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/cyrus-imapd-debugsource-3.8.2-1.fc41.x86_64.rpm
URL 'https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/cyrus-imapd-debugsource-3.8.2-1.fc41.x86_64.rpm' not followed (parent ascending not allowed)
Adding URL: https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/cyrus-imapd-devel-3.8.2-1.fc41.x86_64.rpm
URL 'https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/cyrus-imapd-devel-3.8.2-1.fc41.x86_64.rpm' not followed (parent ascending not allowed)
Adding URL: https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/cyrus-imapd-doc-extra-3.8.2-1.fc41.noarch.rpm
URL 'https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/cyrus-imapd-doc-extra-3.8.2-1.fc41.noarch.rpm' not followed (parent ascending not allowed)
Adding URL: https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/cyrus-imapd-libs-3.8.2-1.fc41.x86_64.rpm
URL 'https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/cyrus-imapd-libs-3.8.2-1.fc41.x86_64.rpm' not followed (parent ascending not allowed)
Adding URL: https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/cyrus-imapd-libs-debuginfo-3.8.2-1.fc41.x86_64.rpm
URL 'https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/cyrus-imapd-libs-debuginfo-3.8.2-1.fc41.x86_64.rpm' not followed (parent ascending not allowed)
Adding URL: https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/cyrus-imapd-utils-3.8.2-1.fc41.x86_64.rpm
URL 'https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/cyrus-imapd-utils-3.8.2-1.fc41.x86_64.rpm' not followed (parent ascending not allowed)
Adding URL: https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/cyrus-imapd-utils-debuginfo-3.8.2-1.fc41.x86_64.rpm
URL 'https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/cyrus-imapd-utils-debuginfo-3.8.2-1.fc41.x86_64.rpm' not followed (parent ascending not allowed)
Adding URL: https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/cyrus-imapd-virusscan-3.8.2-1.fc41.x86_64.rpm
URL 'https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/cyrus-imapd-virusscan-3.8.2-1.fc41.x86_64.rpm' not followed (parent ascending not allowed)
Adding URL: https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/cyrus-imapd-virusscan-debuginfo-3.8.2-1.fc41.x86_64.rpm
URL 'https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/cyrus-imapd-virusscan-debuginfo-3.8.2-1.fc41.x86_64.rpm' not followed (parent ascending not allowed)
Adding URL: https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/hw_info.log
URL 'https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/hw_info.log' not followed (parent ascending not allowed)
Adding URL: https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/mock_output.log
URL 'https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/mock_output.log' not followed (parent ascending not allowed)
Adding URL: https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/noarch_rpmdiff.json
URL 'https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/noarch_rpmdiff.json' not followed (parent ascending not allowed)
Adding URL: https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/perl-Cyrus-3.8.2-1.fc41.x86_64.rpm
URL 'https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/perl-Cyrus-3.8.2-1.fc41.x86_64.rpm' not followed (parent ascending not allowed)
Adding URL: https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/perl-Cyrus-debuginfo-3.8.2-1.fc41.x86_64.rpm
URL 'https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/perl-Cyrus-debuginfo-3.8.2-1.fc41.x86_64.rpm' not followed (parent ascending not allowed)
Adding URL: https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/root.log
URL 'https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/root.log' not followed (parent ascending not allowed)
Adding URL: https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/state25.111353.533 local filename = 'rpms/kojipkgs.fedoraproject.org/work/tasks/8411/115298411/state.log'
...
...
25.111353.533 blacklist https://kojipkgs.fedoraproject.org/icons/blank.gif
25.111353.533 blacklist https://kojipkgs.fedoraproject.org/icons/text.gif
25.111353.533 blacklist https://kojipkgs.fedoraproject.org/robots.txt
25.111353.533 blacklist https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/perl-Cyrus-3.8.2-1.fc41.x86_64.rpm
25.111353.533 blacklist https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/cyrus-imapd-debuginfo-3.8.2-1.fc41.x86_64.rpm
25.111353.533 blacklist https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/noarch_rpmdiff.json
25.111353.533 blacklist https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/state.log
25.111353.533 blacklist https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/cyrus-imapd-libs-3.8.2-1.fc41.x86_64.rpm
25.111353.533 blacklist https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/cyrus-imapd-virusscan-3.8.2-1.fc41.x86_64.rpm
25.111353.533 blacklist https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/build.log
25.111353.533 blacklist https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/cyrus-imapd-doc-extra-3.8.2-1.fc41.noarch.rpm
25.111353.533 blacklist https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/cyrus-imapd-3.8.2-1.fc41.src.rpm
25.111353.533 blacklist https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/cyrus-imapd-devel-3.8.2-1.fc41.x86_64.rpm
25.111353.533 blacklist https://kojipkgs.fedoraproject.org/icons/back.gif
25.111353.533 blacklist https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/?C=N;O=D
25.111353.533 blacklist https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/?C=M;O=A
25.111353.533 blacklist https://kojipkgs.fedoraproject.org/work/tasks/8411/
25.111353.533 blacklist https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/cyrus-imapd-virusscan-debuginfo-3.8.2-1.fc41.x86_64.rpm
25.111353.533 blacklist https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/?C=D;O=A
25.111353.533 blacklist https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/cyrus-imapd-utils-3.8.2-1.fc41.x86_64.rpm
25.111353.533 blacklist https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/mock_output.log
25.111353.533 blacklist https://kojipkgs.fedoraproject.org/icons/unknown.gif
25.111353.533 blacklist https://kojipkgs.fedoraproject.org//work/tasks/8411/115298411/
25.111353.533 blacklist https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/root.log
25.111353.533 blacklist https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/cyrus-imapd-utils-debuginfo-3.8.2-1.fc41.x86_64.rpm
25.111353.533 blacklist https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/hw_info.log
25.111353.533 blacklist https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/perl-Cyrus-debuginfo-3.8.2-1.fc41.x86_64.rpm
25.111353.533 blacklist https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/cyrus-imapd-libs-debuginfo-3.8.2-1.fc41.x86_64.rpm
25.111353.533 blacklist https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/cyrus-imapd-debugsource-3.8.2-1.fc41.x86_64.rpm
25.111353.533 blacklist https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/?C=S;O=A
25.111353.533 blacklist https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/cyrus-imapd-3.8.2-1.fc41.x86_64.rpm
.log
URL 'https://kojipkgs.fedoraproject.org/work/tasks/8411/115298411/state.log' not followed (parent ascending not allowed)
```

So for some reason, even the leaf dir 115298411 where all the .rpm lie is filtered out with this message:"not followed (parent ascending not allowed)". Interesting is also the start of the debug log that states this:
```
25.111353.343 name=parent value=--directory-prefix invert=1
25.111353.343 name=directory-prefix value=rpms invert=0
25.111353.343 name=parent value=--directory-prefix invert=1
25.111353.343 name=directory-prefix value=rpms invert=0
```
Not sure what happens when --no-parent is being parsed and value --directory-prefix is fed to it. If, however, I run the command and set --no-parent to 0, it works as expected:
```
$ wget2 -d -r -l1 --no-parent=0 --directory-prefix rpms -A ".rpm" https://kojipkgs.fedoraproject.org//work/tasks/8411/115298411/
...
$ ls rpms/kojipkgs.fedoraproject.org/work/tasks/8411/115298411/
cyrus-imapd-3.8.2-1.fc41.src.rpm                 cyrus-imapd-libs-debuginfo-3.8.2-1.fc41.x86_64.rpm
cyrus-imapd-3.8.2-1.fc41.x86_64.rpm              cyrus-imapd-utils-3.8.2-1.fc41.x86_64.rpm
cyrus-imapd-debuginfo-3.8.2-1.fc41.x86_64.rpm    cyrus-imapd-utils-debuginfo-3.8.2-1.fc41.x86_64.rpm
cyrus-imapd-debugsource-3.8.2-1.fc41.x86_64.rpm  cyrus-imapd-virusscan-3.8.2-1.fc41.x86_64.rpm
cyrus-imapd-devel-3.8.2-1.fc41.x86_64.rpm        cyrus-imapd-virusscan-debuginfo-3.8.2-1.fc41.x86_64.rpm
cyrus-imapd-doc-extra-3.8.2-1.fc41.noarch.rpm    perl-Cyrus-3.8.2-1.fc41.x86_64.rpm
cyrus-imapd-libs-3.8.2-1.fc41.x86_64.rpm         perl-Cyrus-debuginfo-3.8.2-1.fc41.x86_64.rpm
```

**Comment by rockdaboot** [comment] 2024-03-25 18:25
Thanks for the report. It is reproducible for me and it looks like a bug.

**Comment by rockdaboot** [comment] 2024-03-28 17:46
Fixed by https://gitlab.com/gnuwget/wget2/-/merge_requests/542

**Closed by rockdaboot** 2024-03-28 17:46 UTC
Labels: bug
