### ISSUE TITLE
Executing Wget2 under valgrind reveals reachable blocks in /bin/bash

### ISSUE THREAD

**Issue by darnir** [rockdaboot/wget2#58] opened 2016-01-23 09:49 UTC
I tried running the Wget2 test suite under valgrind and came across interesting results. There might be some memory leaks since 23/25 tests fail, but the more interesting result was that Valgrind is reporting reachable blocks in /bin/bash. The following command line, with no local server running can be used to reproduce the issue on my system:

     valgrind -v --error-exitcode=301 --leak-check=yes --show-reachable=yes --track-origins=yes /src/wget2  'http://localhost:34039/index.html' 2>&1

This causes output of the form:

> ==29190== 3,072 bytes in 192 blocks are indirectly lost in loss record 768 of 773
> ==29190==    at 0x4C28C10: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
> ==29190==    by 0x46B9EA: xmalloc (in /usr/bin/bash)
> ==29190==    by 0x420DF6: ??? (in /usr/bin/bash)
> ==29190==    by 0x423098: yyparse (in /usr/bin/bash)
> ==29190==    by 0x41A69A: parse_command (in /usr/bin/bash)
> ==29190==    by 0x41A767: read_command (in /usr/bin/bash)
> ==29190==    by 0x41A948: reader_loop (in /usr/bin/bash)
> ==29190==    by 0x419445: main (in /usr/bin/bash)
> ==29190== 
> ==29190== 3,323 bytes in 77 blocks are still reachable in loss record 769 of 773
> ==29190==    at 0x4C28C10: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
> ==29190==    by 0x46B9EA: xmalloc (in /usr/bin/bash)
> ==29190==    by 0x4383D6: initialize_shell_variables (in /usr/bin/bash)
> ==29190==    by 0x417CA6: ??? (in /usr/bin/bash)
> ==29190==    by 0x418DE8: main (in /usr/bin/bash)

Does anyone know why valgrind is doing this? The actual log file generated is 4.3MB large, entirely filled with these indirect loss reports for bash.

**Comment by rockdaboot** [comment] 2016-01-23 18:46
I don't see these messages on Debian unstable. Valgrind 3.11.0, bash 4.3-14+b1, glibc 2.21-6.

**Comment by rockdaboot** [comment] 2016-01-23 18:48
```
TESTS_ENVIRONMENT="VALGRIND_TESTS=1" make check
...
# TOTAL: 25
# PASS:  25
```

**Comment by rockdaboot** [comment] 2016-01-23 18:50
It could be that some of the underlying libraries on your system have leaks or valgrind itself is buggy ?

I guess with Arch Linux you are really on the 'bleeding' edge :-)

**Comment by darnir** [comment] 2016-01-23 22:52
I guess it is!

Though the versions I'm using aren't too different:
valgrind: 3.11.0
Bash: 4.3.042
glibc: 2.22

I'll spend some more time trying to figure this out. This is why I wanted to get Valgrind tests running on Travis, so I can check if the issue if my machine or the code in general

**Comment by rockdaboot** [comment] 2016-03-28 18:38
Any news on this ? Can we close it ?

**Comment by darnir** [comment] 2016-04-01 14:43
No. It is still reproducable on Arch and I'm no closer to solving it. Haven't been able to figure out what exactly is causing it

**Comment by rockdaboot** [comment] 2016-04-01 18:05
The above valgrind output does not refer wget2, just bash. Do you see the same with any other command, e.g. ls ? Are you sure that you did not call the libtool wrapper for wget2 ? It is a shell script... In master branch, I already work around that by creating a special wget2 binary that is used by make check. Rebase onto master and try it again, please.

**Comment by rockdaboot** [comment] 2016-04-03 11:18
@darnir I just installed an Arch Linux bootstrap/chroot environment, installed the needed dev stuff and... valgrind check with wget2 runs perfectly (without any bash related messages).

The question is: How to reproduce this issue ?

**Comment by rockdaboot** [comment] 2016-04-03 11:25
@darnir Sorry, I can reproduce it now with your command line from above:

`valgrind -v --error-exitcode=301 --leak-check=yes --show-reachable=yes --track-origins=yes src/wget2  'http://localhost:34039/index.html' 2>&1`

The problem is the libtool wget2 wrapper. Without it (using wget2_noinstall), everything works fine:

`valgrind -v --error-exitcode=301 --leak-check=yes --show-reachable=yes --track-origins=yes src/wget2_noinstall --tries=1 'http://localhost:34039/index.html' 2>&1`

My conclusion is, that this issue is not wget2 related (maybe bash/libtool/valgrind).
I close this issue. Feel free to reopen if you find evidence against wget2.

**Closed by rockdaboot** 2016-04-03 11:25 UTC
Labels: help wanted
