### ISSUE TITLE
error "Compression type (null) not supported"

### ISSUE THREAD

**Issue by stijnsanders** [rockdaboot/wget2#346] opened 2024-09-20 21:27 UTC
I get error "Compression type (null) not supported" on this URL:

https://www.france-figurines.fr/module/feederss/rss

**Comment by rockdaboot** [comment] 2024-09-22 09:11
I can't reproduce this with the given URL. Can you add `--debug` and provide the output, please.

**Comment by rockdaboot** [comment] 2024-09-22 09:26
No I got it. You specified an unknown compression type with `--compression`.
The error message has been fixed now.
Thanks for the report.

**Closed** 2024-09-22 09:26 UTC

**Comment by stijnsanders** [comment] 2024-09-22 15:58
Yes, apparently I had `--compression=auto` which I overlooked. I also notice I get a `Content-Length: 0` response when I add `--header "Accept: application/rss+xml, application/atom+xml, application/xml, text/xml"`, but a correct response without. This is an issue of the hosting server and not wget2, so I don't think anything is wrong there. Thanks for checking!
