### ISSUE TITLE
compiled version will no longer log to a file

### ISSUE THREAD

**Issue by catharsis71** [rockdaboot/wget2#267] opened 2022-10-09 01:13 UTC
I spent the whole day recompiling the program in various ways & messing with libraries trying to get a reasonably reliable executable

All of today's compiles will not log to a file, which is not an issue I had previously

I think yesterday & before I was compiling from https://github.com/rockdaboot/wget2/files/8785830/wget2-2.0.1.tar.gz whereas today I was compiling from https://gnuwget.gitlab.io/wget2/wget2-latest.tar.gz which still claims to be 2.0.1 but actually seems to be newer

Anyway today I'm not having any success trying to log to a file.  The log.txt is either not created, or if it already existed, it's blanked out to 0 bytes but nothing further is written to it

Instead I'm getting really weird glitchy progress bars that don't make a lot of sense and tend to go above 100% (700% being the highest I've seen)

one example:

```
XXXXXXXXX:~/wget2/wget2-2.0.1/src$ ./wget2 --version
GNU Wget2 2.0.1 - multithreaded metalink/file/website downloader

+digest +https +ssl/gnutls +ipv6 +iri +large-file +nls -ntlm -opie +psl -hsts
+iconv +idn2 +zlib -lzma +brotlidec +zstd -bzip2 +lzip +http2 +gpgme

Copyright (C) 2012-2015 Tim Ruehsen
Copyright (C) 2015-2021 Free Software Foundation, Inc.

License GPLv3+: GNU GPL version 3 or later
<http://www.gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Please send bug reports and questions to <bug-wget@gnu.org>.
XXXXXXXXX:~/wget2/wget2-2.0.1/src$ ./wget2 -o log.txt -v -m https://crackypedia.uk/
226 files            101% [==========================================================================================================================================================================================================>]    9.16M    --.-KB/ss
188 files            103% [==========================================================================================================================================================================================================>]    1.94M   67.41KB/s
138 files            104% [==========================================================================================================================================================================================================>]    2.69M   39.08KB/s/
172 files            100% [==========================================================================================================================================================================================================>]    5.29M   29.43KB/s
203 files            100% [==========================================================================================================================================================================================================>]    5.80M   70.87KB/s
                          [Files: 927  Bytes: 24.91M [5.81MB/s] Redirects: 0  Todo: 0  Errors: 0                                                                                                                                      ]
XXXXXXXXX:~/wget2/wget2-2.0.1/src$ cat log.txt
cat: log.txt: No such file or directory
XXXXXXXXX:~/wget2/wget2-2.0.1/src$ ./wget2 -o log.txt -v -m https://crackypedia.uk/
10 files               0% [ <=>                                                                                                                                                                                                       ]   21.70K   22.08KB/s
13 files               0% [   <=>                                                                                                                                                                                                     ]   33.33K   12.35KB/s
9 files                0% [     <=>                                                                                                                                                                                                   ]   23.79K   37.95KB/s
13 files               0% [   <=>                                                                                                                                                                                                     ]   27.09K   10.27KB/s
8 files                0% [   <=>                                                                                                                                                                                                     ]   18.39K   14.89KB/s
                          [Files: 53  Bytes: 124.33K [19.13KB/s] Redirects: 0  Todo: 0  Errors: 0                                                                                                                                     ]
XXXXXXXXX:~/wget2/wget2-2.0.1/src$ cat log.txt
cat: log.txt: No such file or directory
XXXXXXXXX:~/wget2/wget2-2.0.1/src$
XXXXXXXXX@DESKTOP-7TV3RC3:~/wget2/wget2-2.0.1/src$ rm -rf crackypedia.uk/
XXXXXXXXX@DESKTOP-7TV3RC3:~/wget2/wget2-2.0.1/src$ echo TEST > log.txt
XXXXXXXXX@DESKTOP-7TV3RC3:~/wget2/wget2-2.0.1/src$ cat log.txt
TEST
XXXXXXXXX@DESKTOP-7TV3RC3:~/wget2/wget2-2.0.1/src$ ./wget2 -o log.txt -v -m https://crackypedia.uk/
195 files            102% [==========================================================================================================================================================================================================>]    4.52M   56.87KB/s
104 files            100% [==========================================================================================================================================================================================================>]    3.13M   16.28KB/s
290 files            103% [==========================================================================================================================================================================================================>]    4.77M  523.92KB/ss152 files            101% [==========================================================================================================================================================================================================>]    7.05M   89.24KB/s
186 files            101% [==========================================================================================================================================================================================================>]    5.41M   19.98KB/s
                          [Files: 927  Bytes: 24.91M [5.52MB/s] Redirects: 0  Todo: 0  Errors: 0                                                                                                                                      ]
XXXXXXXXX@DESKTOP-7TV3RC3:~/wget2/wget2-2.0.1/src$ cat log.txt
XXXXXXXXX@DESKTOP-7TV3RC3:~/wget2/wget2-2.0.1/src$ l -l log.txt
-rw-r--r-- 1 XXXXXXXXX XXXXXXXXX 0 Oct  8 20:09 log.txt
XXXXXXXXX@DESKTOP-7TV3RC3:~/wget2/wget2-2.0.1/src$
```

This particular executable was built with a no-argument ```./configure``` although I have other executables built various ways including versions for all 3 TLS libraries, and they all behave the same way

I am on Ubuntu WSL 22.04.1 LTS

**Comment by catharsis71** [comment] 2022-10-10 22:32
I see that I can get a proper log file by doing ```--progress none``` combined with ```-o log.txt``` but shouldn't it be possible to leave the progress bar on while also sending  a proper log into the specified output file?

**Comment by rockdaboot** [comment] 2022-10-31 10:36
Just pushed a fix that switches off the progress bar when using -o/--output-file. Wget2 has no dotted bar (yet) that allows mixing bar output with log output.

**Closed by rockdaboot** 2022-10-31 10:36 UTC

**Comment by rockdaboot** [comment] 2022-10-31 10:40
Btw, values > 100% is due to compression. So if the server says 1000 bytes plus gzip compression, wget2 does on-the-fly decompression and calculates the ration of uncompressed bytes and what the server said.
This was fixed once - so maybe a regression or the fix was incomplete ... will check.
