### ISSUE TITLE
Failing to build on macOS Big Sur 11.2

### ISSUE THREAD

**Issue by K20shores** [rockdaboot/wget2#238] opened 2021-02-05 14:29 UTC
I have tried building wget2 both from the tarball and by cloning the repository and building from there. Each time the build fails on the `make` step with the error below.

```
[kyle] ~/Downloads/wget2-1.99.2 $ make -j4
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in lib
  GEN      alloca.h
  GEN      byteswap.h
  GEN      ctype.h
  GEN      arpa/inet.h
  GEN      dirent.h
  GEN      fcntl.h
  GEN      fnmatch.h
  GEN      glob.h
  GEN      inttypes.h
  GEN      langinfo.h
  GEN      limits.h
  GEN      locale.h
  GEN      netdb.h
  GEN      poll.h
  GEN      sched.h
  GEN      signal.h
  GEN      spawn.h
  GEN      stdint.h
  GEN      stdio.h
  GEN      stdlib.h
  GEN      string.h
  GEN      strings.h
  GEN      sys/file.h
  GEN      sys/ioctl.h
  GEN      sys/select.h
  GEN      sys/socket.h
  GEN      sys/random.h
  GEN      sys/stat.h
  GEN      sys/time.h
  GEN      sys/uio.h
  GEN      sys/types.h
  GEN      time.h
  GEN      unistd.h
  GEN      sys/wait.h
  GEN      unitypes.h
  GEN      uniwidth.h
  GEN      utime.h
  GEN      wchar.h
  GEN      wctype.h
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
  CC       openat-proc.lo
  CC       basename-lgpl.lo
  CC       binary-io.lo
  CC       bitrotate.lo
  CC       c-ctype.lo
  CC       c-strcasecmp.lo
  CC       c-strncasecmp.lo
  CC       c-strcasestr.lo
  CC       canonicalize.lo
  CC       cloexec.lo
  CC       concat-filename.lo
  CC       af_alg.lo
  CC       md2.lo
  CC       md5.lo
  CC       sha1.lo
  CC       sha256.lo
  CC       sha512.lo
  CC       dirname.lo
  CC       basename.lo
  CC       dirname-lgpl.lo
  CC       stripslash.lo
  CC       exitfail.lo
  CC       fatal-signal.lo
  CC       fd-hook.lo
  CC       fd-safer-flag.lo
  CC       dup-safer-flag.lo
  CC       file-set.lo
  CC       filenamecat-lgpl.lo
  CC       findprog-in.lo
  CC       freading.lo
  CC       getprogname.lo
  CC       gettime.lo
  CC       hard-locale.lo
  CC       hash.lo
  CC       hash-pjw.lo
  CC       hash-triple-simple.lo
  CC       localcharset.lo
  CC       localename.lo
  CC       localename-table.lo
  CC       glthread/lock.lo
  CC       malloca.lo
  CC       openat-die.lo
  CC       pipe2.lo
  CC       pipe2-safer.lo
  CC       progname.lo
  CC       safe-read.lo
  CC       safe-write.lo
  CC       save-cwd.lo
  CC       malloc/scratch_buffer_dupfree.lo
  CC       malloc/scratch_buffer_grow.lo
  CC       malloc/scratch_buffer_grow_preserve.lo
  CC       malloc/scratch_buffer_set_array_size.lo
  CC       setlocale_null.lo
  CC       sig-handler.lo
  CC       sockets.lo
  CC       spawn-pipe.lo
  CC       stat-time.lo
  CC       strnlen1.lo
  CC       sys_socket.lo
  CC       tempname.lo
  CC       glthread/thread.lo
  CC       glthread/threadlib.lo
  CC       timespec.lo
  CC       u64.lo
  CC       unistd.lo
  CC       dup-safer.lo
  CC       fd-safer.lo
  CC       pipe-safer.lo
  CC       utimens.lo
  CC       wait-process.lo
  CC       wctype-h.lo
  CC       xmalloc.lo
  CC       xalloc-die.lo
  CC       xgethostname.lo
  CC       xsize.lo
  CC       xstrndup.lo
  CC       asnprintf.lo
  CC       canonicalize-lgpl.lo
  CC       chdir-long.lo
  CC       error.lo
  CC       fclose.lo
  CC       fflush.lo
  CC       fnmatch.lo
  CC       fopen.lo
  CC       fpurge.lo
  CC       free.lo
  CC       fseek.lo
  CC       fseeko.lo
  CC       fstatat.lo
  CC       futimens.lo
  CC       getcwd.lo
  CC       getcwd-lgpl.lo
  CC       getlogin_r.lo
  CC       getrandom.lo
  CC       glob.lo
  CC       glob_pattern_p.lo
  CC       globfree.lo
  CC       ioctl.lo
  CC       link.lo
  CC       lstat.lo
  CC       mempcpy.lo
  CC       memrchr.lo
  CC       nanosleep.lo
  CC       nl_langinfo.lo
  CC       open.lo
  CC       openat.lo
  CC       poll.lo
  CC       printf-args.lo
  CC       printf-parse.lo
  CC       qsort_r.lo
  CC       random_r.lo
  CC       rawmemchr.lo
  CC       readlink.lo
  CC       regex.lo
  CC       rename.lo
  CC       setlocale.lo
  CC       setlocale-lock.lo
  CC       spawn.lo
In file included from regex.c:74:
In file included from ./regexec.c:1362:
./malloc/dynarray-skeleton.c:195:13: error: expected identifier or '('
__nonnull ((1))
            ^
./malloc/dynarray-skeleton.c:195:13: error: expected ')'
./malloc/dynarray-skeleton.c:195:12: note: to match this '('
__nonnull ((1))
           ^
./malloc/dynarray-skeleton.c:205:40: error: expected identifier or '('
__attribute_maybe_unused__ __nonnull ((1))
                                       ^
./malloc/dynarray-skeleton.c:205:40: error: expected ')'
./malloc/dynarray-skeleton.c:205:39: note: to match this '('
__attribute_maybe_unused__ __nonnull ((1))
                                      ^
./malloc/dynarray-skeleton.c:216:13: error: expected identifier or '('
__nonnull ((1))
            ^
./malloc/dynarray-skeleton.c:216:13: error: expected ')'
./malloc/dynarray-skeleton.c:216:12: note: to match this '('
__nonnull ((1))
           ^
./malloc/dynarray-skeleton.c:225:13: error: expected identifier or '('
__nonnull ((1))
            ^
./malloc/dynarray-skeleton.c:225:13: error: expected ')'
./malloc/dynarray-skeleton.c:225:12: note: to match this '('
__nonnull ((1))
           ^
./malloc/dynarray-skeleton.c:239:13: error: expected identifier or '('
__nonnull ((1))
            ^
./malloc/dynarray-skeleton.c:239:13: error: expected ')'
./malloc/dynarray-skeleton.c:239:12: note: to match this '('
__nonnull ((1))
           ^
./malloc/dynarray-skeleton.c:248:13: error: expected identifier or '('
__nonnull ((1))
            ^
./malloc/dynarray-skeleton.c:248:13: error: expected ')'
./malloc/dynarray-skeleton.c:248:12: note: to match this '('
__nonnull ((1))
           ^
./malloc/dynarray-skeleton.c:260:13: error: expected identifier or '('
__nonnull ((1))
            ^
./malloc/dynarray-skeleton.c:260:13: error: expected ')'
./malloc/dynarray-skeleton.c:260:12: note: to match this '('
__nonnull ((1))
           ^
./malloc/dynarray-skeleton.c:270:13: error: expected identifier or '('
__nonnull ((1))
            ^
./malloc/dynarray-skeleton.c:270:13: error: expected ')'
./malloc/dynarray-skeleton.c:270:12: note: to match this '('
__nonnull ((1))
           ^
./malloc/dynarray-skeleton.c:286:7: error: implicit declaration of function 'regmatch_list_mark_failed' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
      DYNARRAY_NAME (mark_failed) (list);
      ^
./malloc/dynarray-skeleton.c:151:29: note: expanded from macro 'DYNARRAY_NAME'
#define DYNARRAY_NAME(name) DYNARRAY_CONCAT1(DYNARRAY_PREFIX, name)
                            ^
./malloc/dynarray-skeleton.c:150:40: note: expanded from macro 'DYNARRAY_CONCAT1'
#define DYNARRAY_CONCAT1(prefix, name) DYNARRAY_CONCAT0(prefix, name)
                                       ^
./malloc/dynarray-skeleton.c:149:40: note: expanded from macro 'DYNARRAY_CONCAT0'
#define DYNARRAY_CONCAT0(prefix, name) prefix##name
                                       ^
<scratch space>:231:1: note: expanded from here
regmatch_list_mark_failed
^
In file included from regex.c:74:
In file included from ./regexec.c:1362:
./malloc/dynarray-skeleton.c:297:13: error: expected identifier or '('
__nonnull ((1))
            ^
./malloc/dynarray-skeleton.c:297:13: error: expected ')'
./malloc/dynarray-skeleton.c:297:12: note: to match this '('
__nonnull ((1))
           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
  CC       spawn_faction_addchdir.lo
20 errors generated.
make[3]: *** [regex.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
  CC       spawn_faction_addclose.lo
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by rockdaboot** [comment] 2021-02-06 11:40
Could you make a test ?
In your wget2 project directory (be sure you already executed `./bootstrap` once so that the git submodule 'gnulib' is initialized)
```
cd gnulib
git checkout master
cd ..
git commit -m "Update gnulib" gnulib
./bootstrap
./configure
make clean
make
```

And let me know if the issue is still there or not.

**Comment by K20shores** [comment] 2021-02-06 17:35
Running `./bootstrap` after pulling and committing the master branch of gnulib, I got this error:

```
(houston) [kyle] ~/Downloads/wget2 [master] M$ ./bootstrap 
./bootstrap: Bootstrapping from checked-out wget2 sources...
./bootstrap: consider installing git-merge-changelog from gnulib
./bootstrap: getting gnulib files...
./bootstrap: getting translations into po/.reference for wget2...
Last-modified header missing -- time-stamps turned off.
2021-02-06 11:23:11 URL:https://translationproject.org/latest/wget2/ [5859/5859] -> "po/.reference/index.html.tmp" [1]
https://translationproject.org/robots.txt:
2021-02-06 11:23:12 ERROR 404: Not Found.
Last-modified header missing -- time-stamps turned off.
2021-02-06 11:23:12 URL:https://translationproject.org/latest/wget2/?C=N;O=D [5859/5859] -> "po/.reference/index.html?C=N;O=D.tmp" [1]
Last-modified header missing -- time-stamps turned off.
2021-02-06 11:23:12 URL:https://translationproject.org/latest/wget2/?C=M;O=A [5859/5859] -> "po/.reference/index.html?C=M;O=A.tmp" [1]
Last-modified header missing -- time-stamps turned off.
2021-02-06 11:23:12 URL:https://translationproject.org/latest/wget2/?C=S;O=A [5859/5859] -> "po/.reference/index.html?C=S;O=A.tmp" [1]
Last-modified header missing -- time-stamps turned off.
2021-02-06 11:23:12 URL:https://translationproject.org/latest/wget2/?C=D;O=A [5859/5859] -> "po/.reference/index.html?C=D;O=A.tmp" [1]
Last-modified header missing -- time-stamps turned off.
2021-02-06 11:23:13 URL:https://translationproject.org/latest/ [33004] -> "po/.reference/index.html.tmp" [1]
FINISHED --2021-02-06 11:23:16--
Total wall clock time: 5.4s
Downloaded: 6 files, 61K in 0.1s (413 KB/s)
./bootstrap: autopoint --force
Copying file build-aux/config.rpath
Copying file m4/extern-inline.m4
Copying file po/Makevars.template
running: glibtoolize --install --copy
glibtoolize:   error: 'build-aux/config.guess' is newer: use '--force' to overwrite
glibtoolize:   error: 'build-aux/config.sub' is newer: use '--force' to overwrite
glibtoolize:   error: 'build-aux/install-sh' is newer: use '--force' to overwrite
./bootstrap: gnulib/gnulib-tool    --no-changelog   --aux-dir=build-aux   --doc-base=doc   --lib=libgnu   --m4-base=m4/   --source-base=lib/   --tests-base=lib/tests   --local-dir=gl   --makefile-name=gnulib.mk   --libtool --import ...
```

I went ahead and ran the rest of the steps.

`make` seemed to go well, except that anytime libtool was going to be used, this warning was printed:

```
libtool: warning: '-no-install' is ignored for x86_64-apple-darwin20.3.0
libtool: warning: assuming '-no-fast-install' instead
```

When `make` finished, it told me it had some error that I could not discern:

```
Making all in po
/Applications/Xcode.app/Contents/Developer/usr/bin/make wget2.pot-update
sed -e '/^#/d' remove-potcdate.sin > t-remove-potcdate.sed
mv t-remove-potcdate.sed remove-potcdate.sed
package_gnu="yes"; \
	test -n "$package_gnu" || { \
	  if { if (LC_ALL=C find --version) 2>/dev/null | grep GNU >/dev/null; then \
		 LC_ALL=C find -L .. -maxdepth 1 -type f \
			       -size -10000000c -exec grep 'GNU wget2' \
			       /dev/null '{}' ';' 2>/dev/null; \
	       else \
		 LC_ALL=C grep 'GNU wget2' ../* 2>/dev/null; \
	       fi; \
	     } | grep -v 'libtool:' >/dev/null; then \
	     package_gnu=yes; \
	   else \
	     package_gnu=no; \
	   fi; \
	}; \
	if test "$package_gnu" = "yes"; then \
	  package_prefix='GNU '; \
	else \
	  package_prefix=''; \
	fi; \
	if test -n 'bug-wget2@gnu.org' || test 'bug-wget@gnu.org' = '@'PACKAGE_BUGREPORT'@'; then \
	  msgid_bugs_address='bug-wget2@gnu.org'; \
	else \
	  msgid_bugs_address='bug-wget@gnu.org'; \
	fi; \
	case `/usr/local/bin/xgettext --version | sed 1q | sed -e 's,^[^0-9]*,,'` in \
	  '' | 0.[0-9] | 0.[0-9].* | 0.1[0-5] | 0.1[0-5].* | 0.16 | 0.16.[0-1]*) \
	    /usr/local/bin/xgettext --default-domain=wget2 --directory=.. \
	      --add-comments=TRANSLATORS: --keyword=_ --keyword=N_ --flag=_:1:pass-c-format --flag=N_:1:pass-c-format --flag=error:3:c-format --flag=error_at_line:5:c-format ${end_of_xgettext_options+}  --flag=error:3:c-format --flag=error_at_line:5:c-format \
	      --files-from=./POTFILES.in \
	      --copyright-holder='Free Software Foundation, Inc.' \
	      --msgid-bugs-address="$msgid_bugs_address" \
	    ;; \
	  *) \
	    /usr/local/bin/xgettext --default-domain=wget2 --directory=.. \
	      --add-comments=TRANSLATORS: --keyword=_ --keyword=N_ --flag=_:1:pass-c-format --flag=N_:1:pass-c-format --flag=error:3:c-format --flag=error_at_line:5:c-format ${end_of_xgettext_options+}  --flag=error:3:c-format --flag=error_at_line:5:c-format \
	      --files-from=./POTFILES.in \
	      --copyright-holder='Free Software Foundation, Inc.' \
	      --package-name="${package_prefix}wget2" \
	      --package-version='1.99.2' \
	      --msgid-bugs-address="$msgid_bugs_address" \
	    ;; \
	esac
test ! -f wget2.po || { \
	  if test -f ./wget2.pot; then \
	    sed -f remove-potcdate.sed < ./wget2.pot > wget2.1po && \
	    sed -f remove-potcdate.sed < wget2.po > wget2.2po && \
	    if cmp wget2.1po wget2.2po >/dev/null 2>&1; then \
	      rm -f wget2.1po wget2.2po wget2.po; \
	    else \
	      rm -f wget2.1po wget2.2po ./wget2.pot && \
	      mv wget2.po ./wget2.pot; \
	    fi; \
	  else \
	    mv wget2.po ./wget2.pot; \
	  fi; \
	}
test ! -f ./wget2.pot || \
	  test -z "ca.gmo cs.gmo de.gmo eo.gmo es.gmo et.gmo fi.gmo fr.gmo ga.gmo hr.gmo hu.gmo id.gmo it.gmo ja.gmo nb.gmo nl.gmo pl.gmo pt_BR.gmo ro.gmo ru.gmo sk.gmo sr.gmo sv.gmo tr.gmo uk.gmo vi.gmo zh_CN.gmo" || /Applications/Xcode.app/Contents/Developer/usr/bin/make ca.gmo cs.gmo de.gmo eo.gmo es.gmo et.gmo fi.gmo fr.gmo ga.gmo hr.gmo hu.gmo id.gmo it.gmo ja.gmo nb.gmo nl.gmo pl.gmo pt_BR.gmo ro.gmo ru.gmo sk.gmo sr.gmo sv.gmo tr.gmo uk.gmo vi.gmo zh_CN.gmo
/usr/local/bin/msgmerge --update  --lang=ca ca.po wget2.pot
.................................................... done.
rm -f ca.gmo && /usr/local/bin/msgfmt -c --statistics --verbose -o ca.gmo ca.po
ca.po: 45 translated messages, 16 fuzzy translations, 399 untranslated messages.
/usr/local/bin/msgmerge --update  --lang=cs cs.po wget2.pot
..................................................... done.
rm -f cs.gmo && /usr/local/bin/msgfmt -c --statistics --verbose -o cs.gmo cs.po
cs.po: 51 translated messages, 15 fuzzy translations, 394 untranslated messages.
/usr/local/bin/msgmerge --update  --lang=de de.po wget2.pot
..................................................................................................... done.
rm -f de.gmo && /usr/local/bin/msgfmt -c --statistics --verbose -o de.gmo de.po
de.po: 325 translated messages, 54 fuzzy translations, 81 untranslated messages.
/usr/local/bin/msgmerge --update  --lang=eo eo.po wget2.pot
..................................................... done.
rm -f eo.gmo && /usr/local/bin/msgfmt -c --statistics --verbose -o eo.gmo eo.po
eo.po: 51 translated messages, 15 fuzzy translations, 394 untranslated messages.
/usr/local/bin/msgmerge --update  --lang=es es.po wget2.pot
..................................................... done.
rm -f es.gmo && /usr/local/bin/msgfmt -c --statistics --verbose -o es.gmo es.po
es.po: 49 translated messages, 15 fuzzy translations, 396 untranslated messages.
/usr/local/bin/msgmerge --update  --lang=et et.po wget2.pot
..................................................... done.
rm -f et.gmo && /usr/local/bin/msgfmt -c --statistics --verbose -o et.gmo et.po
et.po: 51 translated messages, 15 fuzzy translations, 394 untranslated messages.
/usr/local/bin/msgmerge --update  --lang=fi fi.po wget2.pot
..................................................... done.
rm -f fi.gmo && /usr/local/bin/msgfmt -c --statistics --verbose -o fi.gmo fi.po
fi.po: 49 translated messages, 15 fuzzy translations, 396 untranslated messages.
/usr/local/bin/msgmerge --update  --lang=fr fr.po wget2.pot
........................................................................................................ done.
rm -f fr.gmo && /usr/local/bin/msgfmt -c --statistics --verbose -o fr.gmo fr.po
fr.po: 337 translated messages, 57 fuzzy translations, 66 untranslated messages.
/usr/local/bin/msgmerge --update  --lang=ga ga.po wget2.pot
..................................................... done.
rm -f ga.gmo && /usr/local/bin/msgfmt -c --statistics --verbose -o ga.gmo ga.po
ga.po: 51 translated messages, 15 fuzzy translations, 394 untranslated messages.
/usr/local/bin/msgmerge --update  --lang=hr hr.po wget2.pot
........................................................................................................ done.
rm -f hr.gmo && /usr/local/bin/msgfmt -c --statistics --verbose -o hr.gmo hr.po
hr.po: 337 translated messages, 57 fuzzy translations, 66 untranslated messages.
/usr/local/bin/msgmerge --update  --lang=hu hu.po wget2.pot
..................................................... done.
rm -f hu.gmo && /usr/local/bin/msgfmt -c --statistics --verbose -o hu.gmo hu.po
hu.po: 51 translated messages, 15 fuzzy translations, 394 untranslated messages.
/usr/local/bin/msgmerge --update  --lang=id id.po wget2.pot
..................................................... done.
rm -f id.gmo && /usr/local/bin/msgfmt -c --statistics --verbose -o id.gmo id.po
id.po: 49 translated messages, 15 fuzzy translations, 396 untranslated messages.
/usr/local/bin/msgmerge --update  --lang=it it.po wget2.pot
..................................................... done.
rm -f it.gmo && /usr/local/bin/msgfmt -c --statistics --verbose -o it.gmo it.po
it.po: 51 translated messages, 15 fuzzy translations, 394 untranslated messages.
/usr/local/bin/msgmerge --update  --lang=ja ja.po wget2.pot
........................................................................................................ done.
rm -f ja.gmo && /usr/local/bin/msgfmt -c --statistics --verbose -o ja.gmo ja.po
ja.po: 337 translated messages, 57 fuzzy translations, 66 untranslated messages.
/usr/local/bin/msgmerge --update  --lang=nb nb.po wget2.pot
............................................................................................. done.
rm -f nb.gmo && /usr/local/bin/msgfmt -c --statistics --verbose -o nb.gmo nb.po
nb.po: 206 translated messages, 46 fuzzy translations, 208 untranslated messages.
/usr/local/bin/msgmerge --update  --lang=nl nl.po wget2.pot
..................................................... done.
rm -f nl.gmo && /usr/local/bin/msgfmt -c --statistics --verbose -o nl.gmo nl.po
nl.po: 49 translated messages, 15 fuzzy translations, 396 untranslated messages.
/usr/local/bin/msgmerge --update  --lang=pl pl.po wget2.pot
..................................................... done.
rm -f pl.gmo && /usr/local/bin/msgfmt -c --statistics --verbose -o pl.gmo pl.po
pl.po: 51 translated messages, 15 fuzzy translations, 394 untranslated messages.
/usr/local/bin/msgmerge --update  --lang=pt_BR pt_BR.po wget2.pot
..................................................... done.
rm -f pt_BR.gmo && /usr/local/bin/msgfmt -c --statistics --verbose -o pt_BR.gmo pt_BR.po
pt_BR.po: 51 translated messages, 15 fuzzy translations, 394 untranslated messages.
/usr/local/bin/msgmerge --update  --lang=ro ro.po wget2.pot
........................................................................................................ done.
rm -f ro.gmo && /usr/local/bin/msgfmt -c --statistics --verbose -o ro.gmo ro.po
ro.po: 337 translated messages, 57 fuzzy translations, 66 untranslated messages.
/usr/local/bin/msgmerge --update  --lang=ru ru.po wget2.pot
..................................................... done.
rm -f ru.gmo && /usr/local/bin/msgfmt -c --statistics --verbose -o ru.gmo ru.po
ru.po: 51 translated messages, 15 fuzzy translations, 394 untranslated messages.
/usr/local/bin/msgmerge --update  --lang=sk sk.po wget2.pot
................................................................................................................ done.
rm -f sk.gmo && /usr/local/bin/msgfmt -c --statistics --verbose -o sk.gmo sk.po
sk.po: 105 translated messages, 189 fuzzy translations, 166 untranslated messages.
/usr/local/bin/msgmerge --update  --lang=sr sr.po wget2.pot
........................................................................................................ done.
rm -f sr.gmo && /usr/local/bin/msgfmt -c --statistics --verbose -o sr.gmo sr.po
sr.po: 337 translated messages, 57 fuzzy translations, 66 untranslated messages.
/usr/local/bin/msgmerge --update  --lang=sv sv.po wget2.pot
..................................................... done.
rm -f sv.gmo && /usr/local/bin/msgfmt -c --statistics --verbose -o sv.gmo sv.po
sv.po: 51 translated messages, 15 fuzzy translations, 394 untranslated messages.
/usr/local/bin/msgmerge --update  --lang=tr tr.po wget2.pot
..................................................... done.
rm -f tr.gmo && /usr/local/bin/msgfmt -c --statistics --verbose -o tr.gmo tr.po
tr.po: 51 translated messages, 15 fuzzy translations, 394 untranslated messages.
/usr/local/bin/msgmerge --update  --lang=uk uk.po wget2.pot
........................................................................................................ done.
rm -f uk.gmo && /usr/local/bin/msgfmt -c --statistics --verbose -o uk.gmo uk.po
uk.po: 337 translated messages, 57 fuzzy translations, 66 untranslated messages.
/usr/local/bin/msgmerge --update  --lang=vi vi.po wget2.pot
..................................................... done.
rm -f vi.gmo && /usr/local/bin/msgfmt -c --statistics --verbose -o vi.gmo vi.po
vi.po: 51 translated messages, 15 fuzzy translations, 394 untranslated messages.
/usr/local/bin/msgmerge --update  --lang=zh_CN zh_CN.po wget2.pot
.......................................................................................... done.
rm -f zh_CN.gmo && /usr/local/bin/msgfmt -c --statistics --verbose -o zh_CN.gmo zh_CN.po
zh_CN.po: 173 translated messages, 47 fuzzy translations, 240 untranslated messages.
touch stamp-po
Making all in docs
mkdir -p ./man/man1
PANDOC=pandoc sh ./wget2_md2man.sh ./wget2.md ./man/man1/wget2.1
sed: 1: "/# Wget2/,/^#/{/^# </!d}": extra characters at the end of d command
pandoc -s -f markdown -t texinfo -o ./wget2.texi ./wget2.md
/bin/sh '/Users/kyle/Downloads/wget2/build-aux/missing' makeinfo --force -o ./wget2.info ./wget2.texi
./wget2.texi:3: warning: unrecognized encoding name `UTF-8'.
./wget2.texi:75: Cross reference to nonexistent node `#Copyright' (perhaps incorrect sectioning?).
./wget2.texi:73: Cross reference to nonexistent node `#Author' (perhaps incorrect sectioning?).
./wget2.texi:71: Cross reference to nonexistent node `#See%20Also' (perhaps incorrect sectioning?).
./wget2.texi:69: Cross reference to nonexistent node `#Bugs' (perhaps incorrect sectioning?).
./wget2.texi:67: Cross reference to nonexistent node `#Startup%20File' (perhaps incorrect sectioning?).
./wget2.texi:65: Cross reference to nonexistent node `#Exit%20Status' (perhaps incorrect sectioning?).
./wget2.texi:63: Cross reference to nonexistent node `#Environment' (perhaps incorrect sectioning?).
./wget2.texi:59: Cross reference to nonexistent node `#Plugin%20Options' (perhaps incorrect sectioning?).
./wget2.texi:57: Cross reference to nonexistent node `#Recursive%20Accept/Reject%20Options' (perhaps incorrect sectioning?).
./wget2.texi:54: Cross reference to nonexistent node `#Recursive%20Retrieval%20Options' (perhaps incorrect sectioning?).
./wget2.texi:52: Cross reference to nonexistent node `#HTTPS%20Options' (perhaps incorrect sectioning?).
./wget2.texi:50: Cross reference to nonexistent node `#HTTP%20Options' (perhaps incorrect sectioning?).
./wget2.texi:48: Cross reference to nonexistent node `#Directory%20Options' (perhaps incorrect sectioning?).
./wget2.texi:46: Cross reference to nonexistent node `#Download%20Options' (perhaps incorrect sectioning?).
./wget2.texi:44: Cross reference to nonexistent node `#Logging%20and%20Input%20File%20Options' (perhaps incorrect sectioning?).
./wget2.texi:41: Cross reference to nonexistent node `#Basic%20Startup%20Options' (perhaps incorrect sectioning?).
./wget2.texi:39: Cross reference to nonexistent node `#Option%20Syntax' (perhaps incorrect sectioning?).
./wget2.texi:36: Cross reference to nonexistent node `#Options' (perhaps incorrect sectioning?).
./wget2.texi:34: Cross reference to nonexistent node `#Description' (perhaps incorrect sectioning?).
./wget2.texi:32: Cross reference to nonexistent node `#Synopsis' (perhaps incorrect sectioning?).
./wget2.texi:30: Cross reference to nonexistent node `#Name' (perhaps incorrect sectioning?).
make[2]: *** [wget2.stamp] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by rockdaboot** [comment] 2021-02-06 17:48
TY for the feedback. Good to hear that the `make` step succeeded (I'll update gnulib here ASAP).

The bootstrap issue can be fixed by installing the latest wget or by `./bootstrap --skip-po` (which does not download the language files).

The failing sed command looks like a non-compatible sed on your system. Either install GNU sed or skip the docs with `./configure --disable-doc`.

I'll give you ping here when everything is updated/uploaded.

**Comment by rockdaboot** [comment] 2021-02-07 14:01
@K20shores Made several changes to the build system now. If you could try again latest master (or tarball) with the instructions from my previous comment.

**Comment by K20shores** [comment] 2021-02-07 16:36
@rockdaboot Thanks! I ran the commands below and `wget2` is now installed.

```
git clone https://github.com/rockdaboot/wget2.git
cd wget2
cd gnulib
git checkout master
git pull
cd ..
git commit -m "Update gnulib" gnulib
./bootstrap --skip-po
./configure --disable-doc
make clean
make
```

**Comment by rockdaboot** [comment] 2021-02-07 18:39
@K20shores Thanks for the feedback.

Meanwhile you should not need the gnulib steps any more, so it reduces to
```
git clone https://github.com/rockdaboot/wget2.git
cd wget2
./bootstrap --skip-po
./configure --disable-doc
make clean
make
sudo make install
```

**Closed by rockdaboot** 2021-02-07 18:39 UTC
